### ISSUE TITLE
Undefined function 'discrfcn' in IRhybrid_lsqr (line 688)

### ISSUE THREAD

**Issue by LGL1992** [silviagazzola/bilevel_adaptive_parameterChoice#1]
Hello, I am a student studying inverse problems, and I am very grateful to the author for providing the article code. In the process of running the code, I found an error about an undefined function. In the 688th line of the custom function IRhybrid_lsqr, there is a call to the function discrfcn, and the function discrfcn is not defined yet, so the main program Example1 runs incorrectly.

**Comment by silviagazzola** [comment]
Thank you very much for pointing this issue out. I have now uploaded the relevant function within the `ExtraBilevel' folder.
